Update Azure workflow to support dual authentication and main branch
Co-authored-by: dream30915 <234465883+dream30915@users.noreply.github.com>

diff --git a/.github/workflows/azure-webapps-php.yml b/.github/workflows/azure-webapps-php.yml
--- a/.github/workflows/azure-webapps-php.yml
+++ b/.github/workflows/azure-webapps-php.yml
@@ -1,27 +1,8 @@
-# This workflow will build and push a PHP application to an Azure Web App when a commit is pushed to your default branch.
-#
-# This workflow assumes you have already created the target Azure App Service web app.
-# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-php?pivots=platform-linux
-#
-# To configure this workflow:
-#
-# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
-#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
-#
-# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
-#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
-#
-# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and PHP_VERSION environment variables below.
-#
-# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
-# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples
-
 name: Build and deploy PHP app to Azure Web App
 
 on:
   push:
-    branches: [ "master" ]
+    branches: [ "master", "main" ]
   workflow_dispatch:
 
 env:
@@ -82,7 +63,7 @@ jobs:
     needs: build
     environment:
       name: 'Development'
-      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
+      # url will be set if the deploy step produces webapp-url output
 
     steps:
       - name: Download artifact from build job
@@ -90,10 +71,41 @@ jobs:
         with:
           name: php-app
 
-      - name: 'Deploy to Azure Web App'
+      - name: Deploy using Publish Profile
         id: deploy-to-webapp
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE != '' }}
         uses: azure/webapps-deploy@v2
         with:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
           package: .
+
+      - name: Login to Azure using Service Principal
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE == '' && secrets.AZURE_CREDENTIALS != '' }}
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Deploy using Service Principal
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE == '' && secrets.AZURE_CREDENTIALS != '' }}
+        id: deploy-to-webapp-sp
+        uses: azure/webapps-deploy@v2
+        with:
+          app-name: ${{ env.AZURE_WEBAPP_NAME }}
+          package: .
+
+      - name: Fail if no Azure credentials found
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE == '' && secrets.AZURE_CREDENTIALS == '' }}
+        run: |
+          echo "Error: No Azure credentials found. Add one of the following repository secrets:\n  - AZURE_WEBAPP_PUBLISH_PROFILE (publish profile XML)\n  - AZURE_CREDENTIALS (service principal JSON from 'az ad sp create-for-rbac --sdk-auth')" >&2
+          exit 1
+
+      - name: Set environment URL (if available)
+        if: steps.deploy-to-webapp.outcome == 'success' || steps.deploy-to-webapp-sp.outcome == 'success'
+        run: |
+          # azure/webapps-deploy exposes webapp-url when used; try to set the environment URL if present
+          if [ -n "${{ steps.deploy-to-webapp.outputs.webapp-url }}" ]; then
+            echo "webapp-url=${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_ENV
+          elif [ -n "${{ steps.deploy-to-webapp-sp.outputs.webapp-url }}" ]; then
+            echo "webapp-url=${{ steps.deploy-to-webapp-sp.outputs.webapp-url }}" >> $GITHUB_ENV
+          fi
